title: gici behaj
description: >
  Skupina chlapců od počítačů, kteří mají rádi běh.
permalink: ':title/'
# baseurl: "/"
url: "gici.behaj.cz" # the base hostname & protocol for your site, e.g. http://example.com
# site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: gici behaj
author-img: logo.jpeg
about-author: Skupina chlapců od počítačů, kteří mají rádi běh. 
              <br /><a href="https://www.strava.com/clubs/gici-behaj">Strava.com</a>

# Disqus
# discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
